/*	LPLP - Verificar ruta de Oracle
*/
--Tablespace para tablas
CREATE TABLESPACE "TS_SEGSYL" DATAFILE 'C:\oraclexe\app\oracle\oradata\SEGSYL\TS_SEGSYL' SIZE 300M AUTOEXTEND ON MAXSIZE 
UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;

--Tablespace para indices
CREATE TABLESPACE "TS_SEGSYLIDX" DATAFILE 'C:\oraclexe\app\oracle\oradata\SEGSYL\TS_SEGSYLIDX' SIZE 300M AUTOEXTEND ON MAXSIZE 
UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;

--Tablespacce temporal 
CREATE TEMPORARY TABLESPACE "TS_TEMP_SEGSYL" TEMPFILE 'C:\oraclexe\app\oracle\oradata\SEGSYL\TS_TEMP_SEGSYL' SIZE 32m AUTOEXTEND on 
NEXT 1m EXTENT MANAGEMENT LOCAL;