CREATE USER "DBSEGSYL" PROFILE "DEFAULT" IDENTIFIED BY "DBSEGSYL" 
DEFAULT TABLESPACE "TS_SEGSYL" TEMPORARY TABLESPACE "TEMP" 
QUOTA UNLIMITED ON "TS_SEGSYL"  ACCOUNT UNLOCK;

GRANT CONNECT TO "DBSEGSYL";
GRANT RESOURCE TO "DBSEGSYL";

ALTER SYSTEM SET PROCESSES = 500 SCOPE=SPFILE;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO DBSEGSYL; 