--Eliminado CONSTRAINTS
ALTER TABLE DBSEGSYL.CLASE
   DROP CONSTRAINT CLASE_TIPO_CLASE_FK;

ALTER TABLE DBSEGSYL.CLASE
   DROP CONSTRAINT CLASE_GRUPO_FK;

ALTER TABLE DBSEGSYL.CLASE
   DROP CONSTRAINT CLASE_DIA_FK;

ALTER TABLE DBSEGSYL.CLASE
   DROP CONSTRAINT CLASE_DOCENTE_FK;

ALTER TABLE DBSEGSYL.PLAN_DE_ESTUDIO
   DROP CONSTRAINT PLAN_DE_ESTUDIO_EAP_FK;

ALTER TABLE DBSEGSYL.MATRICULA
   DROP CONSTRAINT MATRICULA_ALUMNO_FK;

ALTER TABLE DBSEGSYL.MATRICULA
   DROP CONSTRAINT MATRICULA_GRUPO_FK;

ALTER TABLE DBSEGSYL.ALUMNO 
	DROP CONSTRAINT ALUMNO_EAP_FK;

ALTER TABLE DBSEGSYL.ALUMNO 
	DROP CONSTRAINT ALUMNO_USUARIO_FK;

ALTER TABLE DBSEGSYL.DOCENTE 
	DROP CONSTRAINT DOCENTE_USUARIO_FK;

ALTER TABLE DBSEGSYL.USUARIO
	DROP CONSTRAINT USUARIO_ROL_FK;

ALTER TABLE DBSEGSYL.SESION 
	DROP CONSTRAINT SESION_CLASE_FK;

ALTER TABLE DBSEGSYL.ASISTENCIA
	DROP CONSTRAINT ASISTENCIA_SESION_FK;

ALTER TABLE DBSEGSYL.ASISTENCIA
	DROP CONSTRAINT ASISTENCIA_USUARIO_FK;

ALTER TABLE DBSEGSYL.TEMA
	DROP CONSTRAINT TEMA_SYLLABUS_FK;

ALTER TABLE DBSEGSYL.REFERENCIA_BIBLIOGRAFICA
	DROP CONSTRAINT REFERENCIA_SYLLABUS_FK;

ALTER TABLE DBSEGSYL.TEMA_X_SESION
	DROP CONSTRAINT TEMA_X_SESION_TEMA_FK;

ALTER TABLE DBSEGSYL.TEMA_X_SESION
	DROP CONSTRAINT TEMA_X_SESION_SESION_FK;

ALTER TABLE DBSEGSYL.VALIDACION_ALUMNO
	DROP CONSTRAINT VAL_ALUMNO_TEMA_X_SESION_FK;

ALTER TABLE DBSEGSYL.VALIDACION_ALUMNO
	DROP CONSTRAINT VAL_ALUMNO_ALUMNO_FK;

ALTER TABLE DBSEGSYL.TEMA_ADICIONAL
	DROP CONSTRAINT TEMA_ADICIONAL_SESION_FK;

ALTER TABLE DBSEGSYL.ASIGNATURA
	DROP CONSTRAINT ASIGNATURA_PLAN_ESTUDIO_FK;

ALTER TABLE DBSEGSYL.ASIGNATURA
	DROP CONSTRAINT ASIGNATURA_REGIMEN_FK;

ALTER TABLE DBSEGSYL.ASIGNATURA_APERTURADA
	DROP CONSTRAINT ASIG_APERTURADA_PERIODO_FK;

ALTER TABLE DBSEGSYL.ASIGNATURA_APERTURADA
	DROP CONSTRAINT ASIG_APERTURADA_ASIGNATURA_FK;

ALTER TABLE DBSEGSYL.ASIGNATURA_APERTURADA
	DROP CONSTRAINT ASIG_APERTURADA_COORDINADOR_FK;

ALTER TABLE DBSEGSYL.GRUPO
	DROP CONSTRAINT GRUPO_ASIG_APERTURADA_FK;

ALTER TABLE DBSEGSYL.SYLLABUS
	DROP CONSTRAINT SYLL_ASIG_APERTURADA_FK;
  
--Eliminando las tablas sin FK, no tienen dependencias con otras tablas

ALTER TABLE DBSEGSYL.PERIODO DROP PRIMARY KEY CASCADE;
DROP TABLE DBSEGSYL.PERIODO CASCADE CONSTRAINTS;

ALTER TABLE DBSEGSYL.EAP DROP PRIMARY KEY CASCADE;
DROP TABLE DBSEGSYL.EAP CASCADE CONSTRAINTS;

ALTER TABLE DBSEGSYL.REGIMEN DROP PRIMARY KEY CASCADE;
DROP TABLE DBSEGSYL.REGIMEN CASCADE CONSTRAINTS;

ALTER TABLE DBSEGSYL.ROL DROP PRIMARY KEY CASCADE;
DROP TABLE DBSEGSYL.ROL CASCADE CONSTRAINTS;

ALTER TABLE DBSEGSYL.DIA DROP PRIMARY KEY CASCADE;
DROP TABLE DBSEGSYL.DIA CASCADE CONSTRAINTS;

ALTER TABLE DBSEGSYL.TIPO_CLASE DROP PRIMARY KEY CASCADE;
DROP TABLE DBSEGSYL.TIPO_CLASE CASCADE CONSTRAINTS;

--Eliminando tablas dependientes 
DROP TABLE DBSEGSYL.CLASE CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.PLAN_DE_ESTUDIO CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.MATRICULA CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.ALUMNO CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.DOCENTE CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.USUARIO CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.SESION CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.ASISTENCIA CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.TEMA CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.REFERENCIA_BIBLIOGRAFICA CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.TEMA_X_SESION CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.TEMA_ADICIONAL CASCADE CONSTRAINTS;
DROP TABLE DBSEGSYL.ASIGNATURA CASCADE CONSTRAINTS; 
DROP TABLE DBSEGSYL.ASIGNATURA_APERTURADA CASCADE CONSTRAINTS; 
DROP TABLE DBSEGSYL.GRUPO CASCADE CONSTRAINTS; 
DROP TABLE DBSEGSYL.SYLLABUS CASCADE CONSTRAINTS; 
DROP TABLE DBSEGSYL.VALIDACION_ALUMNO CASCADE CONSTRAINTS; 
DROP TABLE DBSEGSYL.CODIGO_GENERAL_DET CASCADE CONSTRAINTS; 